---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reflector
  namespace: rook-ceph
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: sa-reflector
          restartPolicy: Never
          containers:
            - name: secret-reflector
              # image: ghcr.io/k8s-at-home/kubectl:v1.22.1
              image: alpine/k8s:1.21.2
              env:
                - name: SECRETS
                  value: "rook-ceph-mon"
              command:
                - "/bin/sh"
                - "/app/secret-reflector.sh"
              volumeMounts:
                - name: secret-reflector
                  mountPath: /app/secret-reflector.sh
                  subPath: secret-reflector.sh
                  readOnly: true
            - name: configmap-reflector
              # image: ghcr.io/k8s-at-home/kubectl:v1.22.1
              image: alpine/k8s:1.21.2
              env:
                - name: CONFIGMAPS
                  value: "rook-ceph-mon-endpoints"
              command:
                - "/bin/sh"
                - "/app/configmap-reflector.sh"
              volumeMounts:
                - name: configmap-reflector
                  mountPath: /app/configmap-reflector.sh
                  subPath: configmap-reflector.sh
                  readOnly: true
          volumes:
            - name: secret-reflector
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: secret-reflector
                      items:
                        - key: secret-reflector.sh
                          path: secret-reflector.sh
            - name: configmap-reflector
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: configmap-reflector
                      items:
                        - key: configmap-reflector.sh
                          path: configmap-reflector.sh
