---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1763
    env:
      TZ: "America/Chicago"
    podAnnotations:
      setGateway: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-auth@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
        hosts:
        - host: "prowlarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "prowlarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
      shared:
        enabled: true
        emptyDir:
          enabled: true
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1000Mi
