---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io
      chart: cilium
      version: 1.11.6
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    cluster:
      name: "${CLUSTER_NAME}"
      id: "${CLUSTER_ID}"
    rollOutCiliumPods: true
    localRedirectPolicy: true
    kubeProxyReplacement: "strict"
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    nativeRoutingCIDR: ${NETWORK_K8S_CLUSTER_CIDR}
    k8sServiceHost: "${CONTROL_PLANE_ENDPOINT}"
    k8sServicePort: 6443
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
    tunnel: "disabled"
    autoDirectNodeRoutes: true
    ipam:
      mode: "kubernetes"
    operator:
      rollOutPods: true
    containerRuntime:
      integration: containerd
    hubble:
      enabled: true
      serviceMonitor:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/appName: hubble
            hajimari.io/icon: lan
          hosts:
            - &host "hubble.${SECRET_DOMAIN}"
          tls:
            - hosts:
                - *host
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
