---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter-brocade
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: snmp-exporter-brocade
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: snmp-exporter-brocade
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-brocade
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: brocade-0
          module:
            - if_mib
          target: 10.75.10.1
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
