---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: coredns
    fullnameOverride: coredns
    rbac:
      create: true
    replicaCount: 3
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
      - "${LB_COREDNS_IP}"
      externalTrafficPolicy: Local
    servers:
    - zones:
      - zone: ${SECRET_DOMAIN}
        scheme: dns://
      port: 53
      plugins:
      # Enables console logging
      - name: log
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Allow automatic reloading of Corefile
      - name: reload
      # Detect forwarding loops
      - name: loop
      # Static hosts
      - name: hosts
        configBlock: |-
          10.75.30.15 s3.${SECRET_DOMAIN}
          10.75.30.15 minio.${SECRET_DOMAIN}
          10.75.30.15 nexus.${SECRET_DOMAIN}
          10.75.30.15 registry.${SECRET_DOMAIN}
          10.75.30.15 registry-cache.${SECRET_DOMAIN}
          10.75.30.15 franxx.${SECRET_DOMAIN}
          10.75.30.15 unifi.${SECRET_DOMAIN}
          10.75.30.15 vault.${SECRET_DOMAIN}
          fallthrough
      # Set up local resolution
      - name: etcd
        configBlock: |-
          stubzones
          path /skydns
          endpoint https://10.75.40.10:2379 https://10.75.40.11:2379 https://10.75.40.12:2379
          tls /etc/coredns/coredns-etcd/cert.pem /etc/coredns/coredns-etcd/key.pem /etc/coredns/coredns-etcd/ca.crt
      # Set up cache
      - name: cache
        parameters: 30
    extraSecrets:
    - name: coredns-etcd
      mountPath: /etc/coredns/coredns-etcd
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - coredns
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 200Mi
        cpu: 50m
      limits:
        memory: 500Mi
