---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr-uhd
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.19.3.9730@sha256:dd64f1786f50ae79013822ce196e3e7bd20db369bd51d63d63c42f7821b77317
    env:
      TZ: "${TIMEZONE}"
      RADARR__INSTANCE_NAME: Radarr (UHD)
      RADARR__PORT: &port 80
      RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
      RADARR__LOG_LEVEL: info
      PUSHOVER_DEBUG: "false"
      PUSHOVER_APP_URL: &host "{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
      RADARR__POSTGRES_HOST: postgres-rw.database
      RADARR__POSTGRES_MAIN_DB: radarr_uhd
      RADARR__POSTGRES_LOG_DB: radarr_uhd_log
      RADARR__POSTGRES_USER:
        valueFrom:
          secretKeyRef:
            name: radarr-uhd-postgres
            key: POSTGRES_USER
      RADARR__POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: radarr-uhd-postgres
            key: POSTGRES_PASSWORD
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          hajimari.io/icon: "movie"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/radarr/dracula.css"><link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/addons/radarr/radarr-4k-logo/radarr-4k-logo.css"></head>';
            sub_filter_once on;
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 5600
    persistence:
      config:
        enabled: true
        existingClaim: radarr-uhd-config-v1
      media:
        enabled: true
        type: nfs
        server: "nas01.${SECRET_PRIVATE_DOMAIN}"
        path: /tank/share
        mountPath: /media
      scripts:
        enabled: true
        type: configMap
        name: radarr-pushover
        subPath: notify.sh
        mountPath: /scripts/pushover-notify.sh
        defaultMode: 0775
        readOnly: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: radarr-pushover
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
