---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.14
    env:
      TZ: "America/Chicago"
    replicas: 3
    service:
      port:
        port: 4000
      additionalServices:
      - enabled: true
        nameSuffix: dns
        type: LoadBalancer
        externalIPs:
        - "${LB_BLOCKY_IP}"
        port:
          port: 53
          name: dns-tcp
          protocol: TCP
          targetPort: 53
        additionalPorts:
        - port: 53
          name: dns-udp
          protocol: UDP
          targetPort: 53
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
      - host: "blocky.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
      tls:
      - hosts:
        - "blocky.${SECRET_DOMAIN}"
    config: |
      upstream:
        externalResolvers:
        - tcp-tls:1.1.1.1:853
        - tcp-tls:1.0.0.1:853
      conditional:
        mapping:
          ${SECRET_DOMAIN}: udp:${LB_COREDNS_IP}
      blocking:
        blackLists:
          ads:
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      clientLookup:
        upstream: udp:${GATEWAY_IP}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    prometheus:
      serviceMonitor:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
