---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: downloads
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-configs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:b948084aaea16a633ed675d0a085df829605ddb940aeba01a392217445074e82
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarrs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:b948084aaea16a633ed675d0a085df829605ddb940aeba01a392217445074e82
              env:
                - name: TZ
                  value: "${TIMEZONE}"
              command:
                - /app/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: radarrs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:b948084aaea16a633ed675d0a085df829605ddb940aeba01a392217445074e82
              env:
                - name: TZ
                  value: "${TIMEZONE}"
              command:
                - /app/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
