---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.41.4.9463-630c9f557@sha256:7e169d17670c8f34bcb1f40500747b1b689c1c2ef7b80e604b968b5375e62022
    env:
      TZ: "${TIMEZONE}"
      ADVERTISE_IP: "http://${SVC_PLEX_ADDR}:32400/"
      ALLOWED_NETWORKS: "10.0.0.0/8,172.16.0.0/16"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hajimari.io/icon: plex
          nginx.ingress.kubernetes.io/configuration-snippet: |
            location = / {
              if ($http_x_plex_device = ""){
                return 301 $scheme://$host/web/index.html;
              }
            }
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 5600
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        type: nfs
        server: "nas01.${SECRET_PRIVATE_DOMAIN}"
        path: /tank/share
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 16000Mi
