---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airsonic
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: airsonic
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: airsonicadvanced/airsonic-advanced
      tag: latest
      pullPolicy: Always
    podSecurityContext:
      runAsUser: 5600
      runAsGroup: 5600
    env:
      TZ: "America/Chicago"
      JAVA_OPTS: "-Xmx2048m -Dserver.forward-headers-strategy=native"
    enableServiceLinks: false
    persistence:
      config:
        enabled: true
        existingClaim: airsonic-config-v1
        mountPath: /var/airsonic
      media-franxx:
        enabled: true
        existingClaim: nfs-media-franxx-pvc
        readOnly: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones-box"
        hosts:
        - host: "listen.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "listen.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: "1024M"
      limits:
        memory: "2048M"
