---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.41.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      #
      # Sources
      #
      sources:
        journal_logs:
          type: vector
          address: 0.0.0.0:6000
          version: "2"
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
        vector_metrics:
          type: internal_metrics
      #
      # Transformations
      #
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      #
      # Sinks
      #
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs_remap
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ custom_app_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
        prometheus_sink:
          type: prometheus_exporter
          inputs:
            - vector_metrics
          address: 0.0.0.0:9090
          # console_debug:
          #   type: console
          #   inputs:
          #     - opnsense_filterlog_logs
          #   target: stdout
          #   encoding:
          #     codec: json
    image:
      repository: timberio/vector
      tag: 0.45.0-debian
    role: Stateless-Aggregator
    replicas: 3
    # env:
    #   - name: VECTOR_LOG
    #     value: debug
    service:
      enabled: true
      type: LoadBalancer
    podMonitor:
      enabled: true
      jobLabel: vector-aggregator
      port: prometheus-sink
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - Stateless-Aggregator
              topologyKey: kubernetes.io/hostname
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: vector-aggregator
            patch:
              - op: add
                path: /spec/loadBalancerIP
                value: "${SVC_VECTOR_AGGREGATOR_ADDR}"
              - op: replace
                path: /spec/externalTrafficPolicy
                value: Local
