---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-data-v1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
