---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-data-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name hajimari
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
